version: '3.8'

services:
  rabbitmq:
    restart: on-failure
    container_name: ${RABBITMQ_HOST}
    env_file: .env
    build:
      context: docker/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  iot_app:
    restart: on-failure
    container_name: ${APP_HOST}
    env_file: .env
    build:
      context: .
    ports:
      - '8080:8080'
    links:
      - rabbitmq


