version: '3.8'

services:
  rabbitmq:
    restart: on-failure
    container_name: ${RABBITMQ_HOST}
    env_file: .env
    build:
      context: docker/rabbitmq
    ports:
      - "5672:5672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

