spring:
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: user
      password: rabbit_password
  datasource:
    password: iot_password&Studi
    username: iot_app
    url: jdbc:mariadb://localhost/iot_bdd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

rabbit:
    ROUTING_KEY_NAME: iot
    EXCHANGE_NAME: studi

security:
  jwt:
    secret-key: $2y$10$RmiaImd0kv0POVu9Vu3SyeR62JL0Cl3vPYNk.b7612llIsuoxZz7S
    expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000 # 7 days




